apiVersion: v1
kind: Pod
metadata:
  labels:
    name: redis-master
    redis-sentinel: "true"
    role: redis-master
  name: redis-master
spec:
  containers:
    - name: redis-master
      image: 58.240.173.172:5000/redis:v1
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: "0.1"
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
    - name: sentinel
      image: 58.240.173.172:5000/redis:v1
      env:
        - name: SENTINEL
          value: "true"
      ports:
        - containerPort: 26379
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: redis-sentinel
