apiVersion: v1
kind: Service
metadata:
  labels:
    name: sentinel
    role: service
  name: redis-sentinel
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    redis-sentinel: "true"

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-sentinel
spec:
  replicas: 2
  selector:
    name: redis-sentinel
  template:
    metadata:
      labels:
        name: redis-sentinel
        redis-sentinel: "true"
        role: sentinel
    spec:
      containers:
      - name: sentinel
        image: 58.240.173.172:5000/redis:v1
        env:
          - name: SENTINEL
            value: "true"
        ports:
          - containerPort: 26379
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-sentinel
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 18Gi
---

apiVersion: v1
kind: Pod
metadata:
  labels:
    name: redis-master
    redis-sentinel: "true"
    role: redis-master
  name: redis-master
spec:
  containers:
    - name: redis-master
      image: 58.240.173.172:5000/redis:v1
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: "0.1"
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
    - name: sentinel
      image: 58.240.173.172:5000/redis:v1
      env:
        - name: SENTINEL
          value: "true"
      ports:
        - containerPort: 26379
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: redis-sentinel

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-master
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 18Gi
---

apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
spec:
  replicas: 2
  selector:
    name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - name: redis
        image: 58.240.173.172:5000/redis:v1
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis-master
