- template:
    src: etcd.json.j2
    dest: /etc/kubernetes/manifests/etcd.json
- template:
    src: kube-apiserver.json.j2
    dest: /etc/kubernetes/manifests/kube-apiserver.json
- template:
    src: kube-controller-manager.json.j2
    dest: /etc/kubernetes/manifests/kube-controller-manager.json
- template:
    src: kube-scheduler.json.j2
    dest: /etc/kubernetes/manifests/kube-scheduler.json
