apiVersion: v1
kind: ReplicationController
metadata:
  name: rocketmq-namesrv
  labels:
    app: rocketmq-namesrv
    version: v3.5.8
spec:
  replicas: 1
  template:
    metadata:
        labels:
          app: rocketmq
    spec:
      containers:
      - image: 58.240.173.172:5000/rocketmq:v3.5.8
        name: rocketmq
        command: ["/home/admin/RocketMQ/devenv/bin/mqnamesrv"]
        ports:
        - containerPort: 8976
          name: listenport
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: rocketmq-namesrv
  labels:
    app: rocketmq-namesrv
    kubernetes.io/name: "RocketMQ"
spec:
  ports:
  - port: 9876
    protocol: TCP
    targetPort: 9876
  selector:
    app: rocketmq
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rockermq-a
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 18Gi
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rocketmq-brokera
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rocketmq-brokera
    spec:
      containers:
      - image: 58.240.173.172:5000/rocketmq:v3.5.8
        name: rocketmq-brokera
        env:
          - name: JAVA_OPT
            value: -server -Xms2g -Xmx2g -Xmn1g -XX:PermSize=128m -XX:MaxPermSize=320m
               -XX:+UseConcMarkSweepGC -XX:+UseCMSCompactAtFullCollection -XX:CMSInitiatingOccupancyFraction=70 -XX:+CMSParallelRemarkEnabled
               -XX:SoftRefLRUPolicyMSPerMB=0 -XX:+CMSClassUnloadingEnabled -XX:SurvivorRatio=8 -XX:+DisableExplicitGC
        command: ["/home/admin/RocketMQ/devenv/bin/mqbroker"]
        args: ["-n","rocketmq-namesrv:9876","-c","/etc/rocketmq/broker.properties"]
        resources:
          limits:
            memory: 3000Mi
          requests:
            memory: 2048Mi
        ports:
        - containerPort: 10911
          name: broker
          protocol: TCP
        volumeMounts:
        - mountPath: /home/admin/store
          name: rockermq-data
      volumes:
      - name: rockermq-data
        persistentVolumeClaim:
          claimName: rockermq-a
