apiVersion: v1
kind: Service
metadata:
  name: rocketmq-namesrv
  labels:
    k8s-app: rocketmq-namesrv
    kubernetes.io/name: "RocketMQ"
spec:
  clusterIP: 10.254.0.4
  ports:
  - port: 9876
    protocol: TCP
    targetPort: listenport
  selector:
    k8s-app: rocketmq-namesrv
