kind: ConfigMap
apiVersion: v1
metadata:
  name: rocketmq-config
  namespace: default
data:
  broker.properties: |-
    storePathRootDir=/home/admin/rocketmq/store/data
    storePathCommitLog=/home/admin/rocketmq/store/commitlog
